services:
  rental-manager:
    build: .
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rental-manager.rule=Host(`hms.appetitico.com`)"
      - "traefik.http.routers.rental-manager.entrypoints=websecure"
      - "traefik.http.routers.rental-manager.tls.certresolver=letsencrypt"
      - "traefik.http.services.rental-manager.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
